### ISSUE TITLE
Feature request: Whitelist default messages language

### ISSUE THREAD

**Issue by alampros** [GertjanReynaert/react-intl-translations-manager#15]
I'd like to be able to configure a language for all default translations. This would essentially treat any message that has a `defaultMessage` as a whitelisted item for the specified language.

```js
{
  ...
  defaultMessagesLanguage: 'en',
}
```

Treat all messages with a `defaultMessage` set as "en" and add to `whitelist_en`.

**Comment by GertjanReynaert** [comment]
I'm not sure why you would need that, since you don't need to maintain your default messages because you already have them in your components themselves. If you want to have a list is all default messages I'd recommend taking a look at the `singleMessagesFile` option.

**Comment by alampros** [comment]
Yes, but the tool still tells me I have untranslated keys for 'en' (which are the defaults). Am I doing something wrong?

**Comment by GertjanReynaert** [comment]
I'm guessing you also include your default language into the languages array? You shouldn't have to do this, since this is a language where you don't need to maintain translations for. You should only have to include languages of which you want to maintain translations ( = all languages except your default language)

If I'm missing something please explain, I might not be fully understanding your issue.

**Comment by alampros** [comment]
Ah, yes - I'm including all languages in the array in order to load the messages later and feed them to `react-intl` based on the user's language choice. If I don't provide the `en` messages, `react-intl` whines very loudly in the console about it.

**Comment by GertjanReynaert** [comment]
Hm, I'm not sure whats wrong, but if I provide `undefined` or an empty object `{}` into the `messages` prop of `IntlProvider`, react-intl correctly falls back to the `defaultMessages`. So I think that excluding your default language from the `react-intl-translations-manager` languages config, and providing an empty object as `en` messages should do the trick? As I think this is more an issue with react-intl than with this package, you might open a new issue there?

I'll close this issue for now, but if you have some more questions, just ask.

**Comment by alampros** [comment]
Alas, an empty object passed to messages still produces the error, but there is a ticket for it open already (yahoo/react-intl/issues/251).

Thanks for the help on this and for all the work on `react-intl-translation-manager`!

**Comment by mirague** [comment]
We also found ourselves wanting to have the default messages in `en.json`, and went for this approach:

```
import manageTranslations, {
  readMessageFiles,
  createSingleMessagesFile,
  getDefaultMessages
} from 'react-intl-translations-manager';

const messagesDirectory = 'src/locales/extractedMessages';
const translationsDirectory = 'src/locales';

// Output Default Messages
const extractedMessages = readMessageFiles(messagesDirectory);
createSingleMessagesFile({
  messages: getDefaultMessages(extractedMessages).messages,
  directory: translationsDirectory,
  fileName: 'en.json'
});

// Manage the Translations
manageTranslations({
  messagesDirectory,
  translationsDirectory,
  languages: ['sv']
});
```

**Comment by alampros** [comment]
Very elegant solution – I'll definitely give it a shot. Thank you!

**Comment by sunknudsen** [comment]
Thanks for sharing @mirague. This is exactly what I was looking for.
