### ISSUE TITLE
No specific order in the generated json 

### ISSUE THREAD

**Issue by gerinjacob** [GertjanReynaert/react-intl-translations-manager#23]
First of all thanks for providing this component. It was really useful.
However, when the json is generated, it does not seem to follow any specific order. Looks as if it picks randomly from individual component files. 
```
{
  "users.button1": "Add",
  "roles.button2": "Delete",
  "roles.button1": "Add",
  "users.button2": "Delete"
 }
```
It will be nice if it is ordered either by alphabetical or by the order in which it is listed in the individual component files.
```
{
  "users.button1": "Add",
  "users.button2": "Delete",
  "roles.button1": "Add",
  "roles.button2": "Delete"
 }
```

**Comment by Moinax** [comment]
+1 

I agree with @gerinjacob , we currently use PhraseApp to translate the sentences and they return a json ordered by key.

It should be great to do it by default, so that will avoid complex diffs in versioning system when we import them back.

Regards,

**Comment by Moinax** [comment]
I see that there is already a PR #17 . I hope this will be merged very soon :)

**Comment by Moinax** [comment]
That's awesome, thanks a lot @GertjanReynaert

**Comment by GertjanReynaert** [comment]
Thx, although most of the praise should go to @bartvanandel since he did this contribution

**Comment by bartvanandel** [comment]
You're welcome!
