### ISSUE TITLE
syntax for function default parameters

### ISSUE THREAD

**Issue by jardakotesovec** [GertjanReynaert/react-intl-translations-manager#34]
I noticed interesting pattern in your source code. I understand its function with some default values for parameters, but why its inclosed inside `{}`? Have not seen this yet, wondering if its babel being permissive or is that actually proper es2015 pattern? :-)

```
export default ({
  messagesDirectory,
  translationsDirectory,
  whitelistsDirectory = translationsDirectory,
  languages = [],
  singleMessagesFile = false,
  detectDuplicateIds = true,
  sortKeys = true,
  printers = {},
  jsonSpaceIndentation = 2,
}) => {
```

**Comment by GertjanReynaert** [comment]
This allows the user to pass an object with al the options instead of having to pass them as separate arguments. You can read more about this in the destructiring section of Babel https://babeljs.io/docs/learn-es2015/

**Comment by jardakotesovec** [comment]
I see, thanks!
