### ISSUE TITLE
default message is the same as value in en.json, but it says untranslated key

### ISSUE THREAD

**Issue by craigcosmo** [GertjanReynaert/react-intl-translations-manager#59]
my translationrunner is like this:

```jsx
import manageTranslations from 'react-intl-translations-manager';
manageTranslations({
	messagesDirectory: 'dist/message',
	translationsDirectory: 'translation',
	languages: ['en', 'sv'] 
});
```

I run the translationrunner.js , after finish, I remove the en.json file then I run the runner again. This time I have a console log looks like this

<img width="366" alt="screen shot 2016-10-11 at 3 09 28 pm" src="https://cloud.githubusercontent.com/assets/538657/19263161/22793a24-8fc5-11e6-9dac-56dd158422fe.png">

why does the plugin think the en.json in not translated, it's the same the default message in my component. aren't they?

**Comment by GertjanReynaert** [comment]
1. You should remove the `en` entry from your config, or the manager will keep regenerating the `en.json` files
2. The manager will log an untranslated warning for every text message that is identical to the default message, unless it is whitelisted, similar to explained in this [issue](https://github.com/GertjanReynaert/react-intl-translations-manager/issues/38)

**Comment by bensventures** [comment]
In my case I wanted the manager to generate the `en` file, because otherwise `React-Intl` complains that it is using the `defaultMessage`. I ended up overriding the provideWhitelistFile core method to put all of the `en` in the whitelist automatically. Probably a bit hacky but just in case here's the code:

```
'use strict';

const Path = require('path');
const manageTranslations = require('react-intl-translations-manager');
const readFile = require('react-intl-translations-manager/dist/readFile').default;
const defaultLang = 'en-GB';

manageTranslations.default({
    messagesDirectory: './descriptors',
    translationsDirectory: './messages/',
    languages: [defaultLang, 'es-ES'], // any language you need
    overrideCoreMethods: {
        provideWhitelistFile: function (lang) {
            let filePath;
            let jsonFile;
            let whitelist;

            if (lang === defaultLang) {
                filePath = Path.join('./messages/', `${lang}.json`);
                jsonFile = readFile(filePath);
                whitelist = jsonFile ? Object.keys(JSON.parse(jsonFile)) : undefined;
            } else {
                filePath = Path.join('./messages/', `whitelist_${lang}.json`);
                jsonFile = readFile(filePath);
                whitelist = jsonFile ? JSON.parse(jsonFile) : undefined;
            }

            return whitelist ? whitelist : undefined;
        }
    }
});
```
What I really wanted to do was override the `reportLanguage` method but it proved more difficult with the number of local methods the original uses.

**Comment by jessepinho** [comment]
@bensventures if you set a `defaultLocale` on `IntlProvider`, it will stop complaining. It complains about the default message because it doesn't know what locale the default message is in.
