### ISSUE TITLE
Unable to specify absolute paths

### ISSUE THREAD

**Issue by sgoll** [GertjanReynaert/react-intl-translations-manager#6]
When using absolute paths for `messagesDirectory` or `translationsDirectory`, no translations get extracted.

The reason for this seems to be multiple occurrences of the following pattern in the code:

```js
Path.join('./', …)
```

This transforms paths such as `/some/file/or/directory` into `some/file/or/directory`, i.e. stripping the leading slash. I can be argued that this is a bug in Path.join(…).

Is there a reason for using Path.join(…) like this?

**Comment by GertjanReynaert** [comment]
Hm, I added the `Path.join` parts in the code to ensure that relative paths would work, but in the same turn I forgot to support absolute paths.

If we can find a way that would fit both absolute and relative paths that would be great. Would you mind sending a pr?

**Comment by sgoll** [comment]
@GertjanReynaert: Shouldn't relative paths work out of the box? In other words, do you remember why `Path.join` without the initial argument `'./'` is not sufficient?

I can prepare a pull request.

**Comment by abossard** [comment]
I have a hard time following your rational of using: Path.join('./', ...). There is not bug in Path.join and relative path work absolutely fine without the './' in any case, because by definition a path is relative if it starts without a slash. 

Path.join('./', ...) is never doing anything, except convert absolute path to relative. Which isn't what you want, I suppose.

```
> var p = require('path')
undefined
> p.join('./', 'localdir/hello')
'localdir/hello'
> p.join('./', '/localdir/hello')
'localdir/hello'
> p.join('./', './localdir/hello')
'localdir/hello'
> p.join('/localdir/hello')
'/localdir/hello'
```

PR incoming....

**Comment by abossard** [comment]
Please have a look at https://github.com/GertjanReynaert/react-intl-translations-manager/compare/master...abossard:patch-1

Should I make a separate issue.

**Comment by GertjanReynaert** [comment]
@abossard `Rational`: I'm afraid it was just me not being familiar with how to work with paths, and just abusing Path.join as a safety fallback for relative paths.

This being said: I created a pr which should fix all incorrect uses of Path.join, would you mind reviewing? https://github.com/GertjanReynaert/react-intl-translations-manager/pull/13

**Comment by abossard** [comment]
I also just learned about how path.join works exactly when I investigated this issue a bit more :-)
