### ISSUE TITLE
Empty extracted translations

### ISSUE THREAD

**Issue by mschipperheyn** [GertjanReynaert/react-intl-translations-manager#64]
Hi,

I'm trying to understand this tool, as it seems to complete successfully, but I get empty files in translationsDirectory and no result in messagesDirectory.

What I expect to happen is that the tool parses my jsx files and extracts message ids from <FormattedMessage id="x"/> statements and intl.formatMessage statements. However, I would also expect a src directory key for it to know where to look for jsx files.

Is this correct?

	import translationManager from 'react-intl-translations-manager';

	translationManager({
	  messagesDirectory: './i8n/extractedMessages',
	  translationsDirectory: './src/resources/i8n/',
	  whitelistsDirectory: './src/i8n/whitelists/',
	  languages: ['pt', 'nl'],
	});

**Comment by GertjanReynaert** [comment]
This tool won't extract your messages, as it expects you to configure the babel-plugin-react-intl in your babel config. The directory you configure for that plugin is the same directory you should configure in your translationManager config:

```
import translationManager from 'react-intl-translations-manager';

translationManager({
  messagesDirectory: <<<directory configured for babel plugin>>>,
  translationsDirectory: './src/resources/i8n/',
  whitelistsDirectory: './src/i8n/whitelists/',
  languages: ['pt', 'nl'],
});```

If the explanation wasn't clear feel free to reopen the issue
