### ISSUE TITLE
Is it possible to know when manageTranslations is finished?

### ISSUE THREAD

**Issue by bensampaio** [GertjanReynaert/react-intl-translations-manager#69]
On my project I am trying to create a script that does the following:
- runs babel to extract the messages
- runs the translations manager to generate the language files
- removes the extracted messages directory (at least I don't see any reason to keep these files...)

The problem is that there is no callback in the `manageTranslations` function and it also doesn't return a Promise... Without this I cannot know when the function is finished so I can delete the extracted messages directory.

Is there any way to accomplish this?

**Comment by GertjanReynaert** [comment]
In the default `manageTranslations` this is indeed not possible, but you can always build your own custom translation manager with the exposed [`core`](https://github.com/GertjanReynaert/react-intl-translations-manager#core). Here you can then use the [`afterReporting`](https://github.com/GertjanReynaert/react-intl-translations-manager#afterreporting) hook to accomplish your remove functionality.

I hope this was helpful, please do not hesitate to reopen and as more details if you still have questions.

**Comment by bensampaio** [comment]
Thank you for the fast answer!

To accomplish what you are saying I would need to call the core function with all the arguments in (manageTranslations.js)[https://github.com/GertjanReynaert/react-intl-translations-manager/blob/master/src/manageTranslations.js]. Am I correct?

If yes, since that seems like a lot of copy paste, would you accept a PR that changes the `manageTranslations.js` to return a `Promise` and call the resolve function in the `afterReporting`? Thanks!

**Comment by bensampaio** [comment]
I actually just tried to implement that but when `afterReporting` is run the `manageTranslations` is not yet finished... I guess there is some async task somewhere? So your suggestion doesn't really work.

I cannot reopen the issue since you were the one closing it.

**Comment by GertjanReynaert** [comment]
Didn't knew that the creator of an issue couldn't reopen it, sorry for that

**Comment by GertjanReynaert** [comment]
There is no async work going on in the [core](https://github.com/GertjanReynaert/react-intl-translations-manager/blob/master/src/core.js), and the file interaction methods use the sync version instead of the async versions. So it sounds a bit weird to me that the translation manager wouldn't be ready yet.

**Comment by bensampaio** [comment]
I just realised what the problem was. I was using the `transformFile` function from `babel-core` instead of `transformFileSync` to generate the JSON files. So `manageTranslations` was being called before all the translation files were there. So my bad... Sorry for bothering you and thank you for the fast replies!

**Comment by LoicUV** [comment]
@bensampaio I'm interested in the same exact process to handle my messages, would you share your code if that's not too much trouble for you ?

**Comment by bensampaio** [comment]
Hi @LoicUV,

Here is a sample of what I did:

```js
#! /usr/bin/env node
const glob = require('glob');
const manageTranslations = require('react-intl-translations-manager').default;
const path = require('path');
const shell = require('shelljs');

// List of file paths that might contain messages to be translated.
const srcPaths = glob.sync(path.resolve(process.cwd(), 'src', '**', '*.js'));

// Temporary path where to store the generated JSON files.
const tmpPath = path.resolve(process.cwd(), 'tmp');

// Output path for the locale translation files.
const outputPath = path.resolve(process.cwd(), 'trans');

// List of languages to support
const languages = ['nl', 'es'];

let exitCode = 0;

try {

    // Generate the JSON files for every file that defines messages.
    for (let filePath of srcPaths) {
        require('babel-core').transformFileSync(filePath, {
            plugins: [
                ['react-intl', { messagesDir: tmpPath }],
            ],
        });
    }

    // Manage the translation files for every language
    manageTranslations({
        languages,
        messagesDirectory: tmpPath,
        singleMessagesFile: true,
        translationsDirectory: outputPath,
    });

}
catch (e) {
    console.error(e);
    exitCode = 1;
}
finally {

    // Remove temporary folder when finished
    shell.exec(`rm -rf ${tmpPath}`, (code) => {
        shell.exit(exitCode || code);
    });

}
```

Then if you are using a tool like [webpack](https://github.com/webpack/webpack) together with [json-loader](https://github.com/webpack/json-loader) you can do something like:

```js
require.ensure('trans/nl.json', (require) => {
    const messages = require('trans/nl.json');
    ReactDOM.render(
        <IntlProvider messages={messages}>
            // your components in here
        </IntlProvider>
    );
});
```

Hope this helps!
