### ISSUE TITLE
Should default language be included in manageTranslations.config.languages

### ISSUE THREAD

**Issue by gruberjl** [GertjanReynaert/react-intl-translations-manager#77]
Looking at the example in the [README.md](https://github.com/GertjanReynaert/react-intl-translations-manager#basic):

```
manageTranslations({
  messagesDirectory: 'src/translations/extractedMessages',
  translationsDirectory: 'src/translations/locales/',
  languages: ['nl'], // does the default language need to be included?
});
```

Should I specify the default language (English)? For example: If I write the app in English, then I want to add Spanish support, should languages be: ['en', 'es'] or ['es']

**Comment by gruberjl** [comment]
I think I answered my own question. No. translation manager will yell at you. Looks like React-intl automatically includes English and the default language, which explains why my package grew after adding it.

Can someone confirm that it shouldn't be added? I'll add a quick note in the `README.md`. I wanted to fix the `require` example anyway. It should be `require().default`

**Comment by GertjanReynaert** [comment]
The default language shouldn't be added to the list of languages, since this is the only language that doesn't need to be 'managed'.

A pr for updating the readme is definitely welcome! thx
